### ISSUE TITLE
Error running apu on Ubuntu 16.04

### ISSUE THREAD

**Issue by ragunathjawahar** [cesarferreira/apu#2]
Previously, I had issues when multiple devices were connected. Now, after disconnecting all devices but one `apu -p todoapp-mvp-dagger -i -o` results in the following error.

```
/var/lib/gems/2.3.0/gems/apu-0.3.7/lib/apu/android_project.rb:64:in `install': undefined local variable or method `execute_line' for #<Apu::AndroidProject:0x000000021af408> (NameError)
Did you mean?  @execute_line
               execution_line
    from /var/lib/gems/2.3.0/gems/apu-0.3.7/lib/apu.rb:61:in `manage_opts'
    from /var/lib/gems/2.3.0/gems/apu-0.3.7/lib/apu.rb:32:in `initialize'
    from /var/lib/gems/2.3.0/gems/apu-0.3.7/bin/apu:5:in `new'
    from /var/lib/gems/2.3.0/gems/apu-0.3.7/bin/apu:5:in `<top (required)>'
    from /usr/local/bin/apu:22:in `load'
    from /usr/local/bin/apu:22:in `<main>'
```

**Comment by cesarferreira** [comment]
update should fix this issue
